# Generated by Django 2.0.1 on 2018-05-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0007_auto_20180525_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamee',
            name='cbad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamee',
            name='cgood',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='clove',
            field=models.TextField(blank=True),
        ),
    ]
