# Generated by Django 2.0.1 on 2018-05-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0008_auto_20180526_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='lovemode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cAuthor', models.TextField(blank=True, max_length=255)),
                ('cContent', models.TextField(blank=True, default='', max_length=99999)),
                ('cTitle', models.CharField(blank=True, default='', max_length=100)),
                ('cLink', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamee',
            name='cbad',
        ),
        migrations.RemoveField(
            model_name='gamee',
            name='cgood',
        ),
    ]
