# Generated by Django 2.0.1 on 2018-05-27 16:56

from django.db import migrations
import gameapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0009_auto_20180527_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='clove',
            field=gameapp.models.ListField(blank=True),
        ),
    ]
